version: '3.7'


# Networks
networks:
  stream-net:
    driver: bridge


services:


# POSTGRESQL
    postgres:
        image: postgres:13
        hostname: postgres
        container_name: postgres
        environment:
            - TZ=America/Araguaina
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        volumes:
            - ./store_files:/blob            
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "airflow"]
            interval: 5s
            retries: 5
        networks:
            - stream-net
        deploy:
            resources:
                limits:
                    memory: 500m
        

# PGADMIN
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        restart: always
        hostname: pgadmin
        environment:
            - TZ=America/Araguaina
            - PGADMIN_DEFAULT_EMAIL=lemes_vilarinho@yahoo.com.br
            - PGADMIN_DEFAULT_PASSWORD=123
        ports:
            - "5050:80"
        networks:
            - stream-net
        deploy:
            resources:
                limits:
                    memory: 500m


# AIRFLOW
    webserver:
        image: thiago/airflow:2.5.1
        # restart: always
        container_name: airflow
        hostname: airflow
        depends_on:
            postgres:
                condition: service_healthy
        env_file:
            - ./config/conf_airflow.env # Configuration Time Zone and SMTP
            - ./config/var_dags.env # Confguring variables in DAGs
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./blob:/usr/local/airflow/blob
            - ./store_files:/usr/local/airflow/store_files_airflow
            - ./sql_files:/usr/local/airflow/sql_files
            - ./plugins:/usr/local/airflow/plugins
            - ./config:/usr/local/airflow/config
        ports:
            - "8080:8080"
        networks:
            - stream-net
